### ISSUE TITLE
[Request/Idea] Decorative Nothingness

### ISSUE THREAD

**Issue by LeapInSoft** [kreezxil/the-god-block#3]
Hello,
I'm currently playing Godblock modpack (1.17.18), sometime Nothingness is hard to see (mostly the night) and I have break block I don't want to break (for aesthetic point of view).
I don't see any craft for Nothingness but it will be cool to have a decorative version who don't drop Quanta.

**Comment by kreezxil** [comment]
or a way to get it back, you did realize that once you get a pick axe you
can vein mine it too?

**Comment by LeapInSoft** [comment]
Thank for your answer !
Sorry if I don't understand you really well, you mean I can undo with OreExcavation ?
Now it is too late but I can go in creative mode for put back some Nothingness.

Anyway I think it could be cool to have some decorative block for Nothingness like block, slab, stair ... :)
Look like Nothingness block don't work with chisel & bits.

**Comment by kreezxil** [comment]
I created this mod so that I could create god block pack.

No I was wondering if you knew that veinmining works on the blocks or not.

**Comment by LeapInSoft** [comment]
I have tried to vienmine it with bare hand and don't know it work with pickaxe, thank for info :)

I know it is for The God Block pack. I play this pack currently and I think it could be a nice addition for the pack. But I don't want to bother you it's only an idea.

**Comment by kreezxil** [comment]
as long as you're nice about it, you can bother me all you want, that's what the tracker is for. Just don't bump it after 2 days or a week.

It's a good idea. I recommend using torches to see them at night.

I'll adjust the blocks to be a shade darker and add in those blocks you were talking about plus a quantum recipe to get just the nothingness back.

right now I"m going to adjust the God Block pack for some immediate issue repair, and then on Sunday I'll give this a whirl, so look for another update of the pack either Sunday or Monday.

**Comment by kreezxil** [comment]
Today's version God Block pack will have a simple recipe to get the block itself back. This should be construed with the features you requested here which will require the additions to the code base of the mod itself.

**Comment by LeapInSoft** [comment]
Nice Thanks !
