### ISSUE TITLE
Can't read zip file

### ISSUE THREAD

**Issue by CaptJack2883** [kreezxil/the-god-block#4]
When I try to install Version 1.18.19, Twitch says it can't read the zip file. Version 1.17.18 downloads and installs fine. Screenshot of error attached, I blanked out my username, but you can see the rest of the file path.
![GodBlock](https://user-images.githubusercontent.com/59985652/75602842-74d20c00-5a8e-11ea-8f8c-2b1f50c6a9b2.JPG)

**Comment by LeapInSoft** [comment]
Here is issues for the God block mod.
But anyway personnaly I don't have any issue with the zip when I download via Curse and use MultiMC

**Comment by kreezxil** [comment]
the problem is with Twitch, MultiMC, ATLauncher, and GDLauncher from
https://gdevs.io don't have this problem.

**Comment by kreezxil** [comment]
Also this is "The God Block" a mod, not the pack.
